-- MySQL Script generated by MySQL Workbench
-- Fri Oct 26 01:04:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sample
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sample` DEFAULT CHARACTER SET utf8 ;
USE `sample` ;

-- -----------------------------------------------------
-- Table `sample`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`products` (
  `idproducts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`idproducts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sample`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`customers` (
  `idcustomers` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sample`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`sellers` (
  `idsellers` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idsellers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sample`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sample`.`sales` (
  `idsales` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `qtd` INT NULL,
  `sellers_idsellers` INT NOT NULL,
  `customers_idcustomers` INT NOT NULL,
  `products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idsales`),
  INDEX `fk_sales_sellers_idx` (`sellers_idsellers` ASC),
  INDEX `fk_sales_customers1_idx` (`customers_idcustomers` ASC),
  INDEX `fk_sales_products1_idx` (`products_idproducts` ASC),
  CONSTRAINT `fk_sales_sellers`
    FOREIGN KEY (`sellers_idsellers`)
    REFERENCES `sample`.`sellers` (`idsellers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_customers1`
    FOREIGN KEY (`customers_idcustomers`)
    REFERENCES `sample`.`customers` (`idcustomers`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `sample`.`products` (`idproducts`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'sampleuser' IDENTIFIED BY 'samplepassword';

GRANT ALL ON `sample`.* TO 'sampleuser';
GRANT SELECT ON TABLE `sample`.* TO 'sampleuser';
GRANT SELECT, INSERT, TRIGGER ON TABLE `sample`.* TO 'sampleuser';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `sample`.* TO 'sampleuser';
/*GRANT EXECUTE ON ROUTINE `sample`.* TO 'sampleuser';*/

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
